versions: 2.1
jobs:
  dry_run:
    docker: 
      - image: ruby:2.5.1
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
        default: "staging"
    steps:
      - run:
          name: dry-run
          command: |
            echo dry-run << parameters.env >>

  apply:
    docker:
      - image: ruby:2.5.1
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
        default: "staging"
    steps:
      - run:
          name: apply
          command: |
            echo apply << parameters.env >>

workflows:
  version: 2
  staging_dry_run:
    jobs:
      - dry_run:
          name: "staging dry-run"
          env: "staging"
          filters:
            branches:
              only: feature/*

  staging_apply:
    jobs:
      - apply:
          name: "staging apply"
          env: "staging"
          requires:
            - staging_dry_run
          filters:
            branches:
              only: staging

  production_dry_run:
    jobs:
      - dry_run:
          name: "production dry-run"
          env: "production"
          filters:
            branches:
              only: staging

  production_apply:
    jobs:
      - apply:
          name: "production apply"
          env: "production"
          requires:
            - production_dry_run
          filters:
            branches:
              only: production


          
      
