version: 2.1
executors:
  default:
    docker: 
      - image: ruby:2.5.1
    working_directory: ~/$CIRCLE_PROJECT_REPONAME

jobs:
  test:
    executor:
      name: default
    steps:
      - run:
          name: echo
          command: echo "Hello, world!" > hoge
            
      - run:
          name: cat
          command: cat hoge

workflows:
  version: 2.1
  wf:
    jobs:
      - test
