versions: 2.1
jobs:
  dry_run:
    docker: 
      - image: ruby:2.5.1
    steps:
      - run:
          name: dry-run
          command: |
            echo dry-run << parameters.apply_to >>
    parameters:
      apply_to:
        type: enum
        enum: ["staging", "production"]
        default: "staging"
    

  apply:
    docker:
      - image: ruby:2.5.1
    steps:
      - run:
          name: apply
          command: |
            echo apply << parameters.apply_to >>
    parameters:
      apply_to:
        type: enum
        enum: ["staging", "production"]
        default: "staging"

workflows:
  version: 2
  staging_dry_run:
    jobs:
      - dry_run:
          apply_to: "staging"
          filters:
            branches:
              only: feature/*

  staging_apply:
    jobs:
      - apply:
          apply_to: "staging"
          requires:
            - staging_dry_run
          filters:
            branches:
              only: staging

  production_dry_run:
    jobs:
      - dry_run:
          apply_to: "production"
          filters:
            branches:
              only: staging

  production_apply:
    jobs:
      - apply:
          apply_to: "production"
          requires:
            - production_dry_run
          filters:
            branches:
              only: production


          
      
